name: Checks
on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
    branches: [main]

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTEST_ADDOPTS: --color=yes
  PIP_PROGRESS_BAR: "off"
  KERNEL_NAME: phreeqcinwt
defaults:
  run:
    # -l: login shell, needed when using Conda:
    shell: bash -l {0}

jobs:
  code-formatting:
    name: Check code is formatted (Black)
    # OS and/or Python version don't make a difference, so we choose ubuntu and 3.12 as defaults
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Black
        # unlike the other jobs, we don't need to install all the dev dependencies,
        # but we still want to specify the Black version to use in requirements-dev.txt for local development
        # so we extract the relevant line and pass it to a simple `pip install`
        run: |
          black_requirement="$(grep '^black==' requirements-dev.txt)"
          pip install "$black_requirement"
      - name: Run Black to verify that the committed code is formatted
        run: |
          black --check .

  pytest-dev:
    name: pytest (${{ matrix.os }}/${{ matrix.python-version }}/${{ matrix.install-mode }}/${{ matrix.pytest_folders }})
    runs-on: ${{ matrix.os-version }}
    needs: [code-formatting]
    strategy:
      fail-fast: false
      matrix:
        install-mode:
          - dev
          - standard
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        os:
          # - linux
          # - mac
          - win64
        include:
          - os: linux
            os-version: ubuntu-22.04 #
          # - os: mac
          #   os-version: macos-15
          - os: win64
            os-version: windows-2022
          - install-mode: dev
            python-version: "3.12"  # choice of Python version is arbitrary among those in matrix
    steps:                        
      - if: matrix.install-mode == 'dev'
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          channels: conda-forge
          activate-environment: phreeqcinwt
      - if: matrix.install-mode == 'dev'
        name: Install via conda.yaml
        run: |
          conda env update --file phreeqcinwt.yaml
          pip list
      - if: matrix.install-mode == 'standard'
        name: Install (standard)
        run: |
          pip install "git+${{ format('{0}/{1}@{2}', github.server_url, github.repository, github.ref) }}"      
      - name: Run pytest
        run: |
          pip install pytest  # ensure pytest is installed (should do nothing if already present from requirements-dev.txt)
          pytest --pyargs phreeqcinwt
           